from datetime import datetime
from decimal import Decimal
import re

from workflows.invoice_autoposting.schemas import AccountingEntry, InvoiceLineItem


def extract_accounting_entry(document_text: str) -> AccountingEntry:
    vendor_name = _extract_vendor_name(document_text)
    invoice_number = _extract_invoice_number(document_text)
    invoice_date = _extract_invoice_date(document_text)
    currency = _extract_currency(document_text)
    subtotal = _extract_amount(document_text, ("subtotal", "sub total"))
    tax_amount = _extract_amount(document_text, ("tax", "vat", "gst"), default=Decimal("0"))
    total_amount = _extract_amount(document_text, ("total", "amount due", "grand total"))

    if subtotal is None:
        subtotal = total_amount - tax_amount

    return AccountingEntry(
        vendor_name=vendor_name,
        invoice_number=invoice_number,
        invoice_date=invoice_date,
        currency=currency,
        subtotal=subtotal,
        tax_amount=tax_amount,
        total_amount=total_amount,
        line_items=[
            InvoiceLineItem(
                description="Imported invoice amount",
                quantity=Decimal("1"),
                unit_price=subtotal,
                amount=subtotal,
            )
        ],
        payment_terms=_extract_payment_terms(document_text),
        explanation="Generated by deterministic invoice fallback parser.",
    )


def _first_match(patterns: list[str], text: str) -> str | None:
    for pattern in patterns:
        match = re.search(pattern, text, flags=re.IGNORECASE | re.MULTILINE)
        if match:
            return match.group(1).strip()
    return None


def _parse_decimal(raw_value: str) -> Decimal:
    normalized = re.sub(r"[^0-9,.\-]", "", raw_value).replace(",", "")
    return Decimal(normalized)


def _parse_date(raw_value: str):
    raw_value = raw_value.strip()
    for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d/%m/%Y", "%d-%m-%Y", "%b %d %Y", "%B %d %Y"):
        try:
            return datetime.strptime(raw_value, fmt).date()
        except ValueError:
            continue
    raise ValueError(f"Unable to parse invoice date from '{raw_value}'.")


def _extract_vendor_name(text: str) -> str:
    explicit_vendor = _first_match(
        [
            r"^vendor[:\s]+(.+)$",
            r"^supplier[:\s]+(.+)$",
            r"^bill from[:\s]+(.+)$",
        ],
        text,
    )
    if explicit_vendor:
        return explicit_vendor

    for line in text.splitlines():
        candidate = line.strip()
        if not candidate:
            continue
        lowered = candidate.lower()
        if any(keyword in lowered for keyword in ("invoice", "date", "total", "subtotal", "tax")):
            continue
        return candidate

    raise ValueError("Unable to determine vendor name from OCR text.")


def _extract_invoice_number(text: str) -> str:
    value = _first_match(
        [
            r"invoice\s*(?:number|no|#)?[:\s-]+([A-Z0-9-]+)",
            r"\bINV[-\s:#]*([A-Z0-9-]+)",
        ],
        text,
    )
    if not value:
        raise ValueError("Unable to determine invoice number from OCR text.")
    return value


def _extract_invoice_date(text: str):
    value = _first_match(
        [
            r"invoice\s*date[:\s]+([A-Za-z0-9,/\- ]+)",
            r"date[:\s]+([A-Za-z0-9,/\- ]+)",
        ],
        text,
    )
    if not value:
        raise ValueError("Unable to determine invoice date from OCR text.")
    return _parse_date(value)


def _extract_currency(text: str) -> str:
    return (
        _first_match(
            [
                r"currency[:\s]+([A-Z]{3})",
                r"\b(USD|EUR|GBP|JPY|TWD|SGD|AUD|CAD)\b",
            ],
            text,
        )
        or "USD"
    )


def _extract_payment_terms(text: str) -> str | None:
    return _first_match([r"payment\s*terms?[:\s]+(.+)$"], text)


def _extract_amount(text: str, labels: tuple[str, ...], default: Decimal | None = None) -> Decimal | None:
    for label in labels:
        match = re.search(
            rf"(?im)^\s*{re.escape(label)}\b[:\s$]*([-+]?\$?[0-9,]+(?:\.[0-9]{{2}})?)",
            text,
        )
        if match:
            return _parse_decimal(match.group(1))
    return default
