from datetime import datetime
from decimal import Decimal
import re

from workflows.invoice_autoposting.schemas import AccountingEntry, InvoiceLineItem


def extract_accounting_entry(document_text: str) -> AccountingEntry:
    vendor_name = _extract_vendor_name(document_text)
    invoice_number = _extract_invoice_number(document_text)
    invoice_date = _extract_invoice_date(document_text)
    currency = _extract_currency(document_text)
    subtotal = _extract_amount(document_text, ("subtotal", "sub total"))
    tax_amount = _extract_amount(document_text, ("tax", "vat", "gst"), default=Decimal("0"))
    total_amount = _extract_amount(document_text, ("total", "amount due", "grand total"))

    if subtotal is None:
        subtotal = total_amount - tax_amount

    line_items = _extract_line_items(document_text, subtotal=subtotal)

    return AccountingEntry(
        vendor_name=vendor_name,
        invoice_number=invoice_number,
        invoice_date=invoice_date,
        currency=currency,
        subtotal=subtotal,
        tax_amount=tax_amount,
        total_amount=total_amount,
        line_items=line_items,
        payment_terms=_extract_payment_terms(document_text),
        explanation="Generated by deterministic invoice fallback parser.",
    )


def _first_match(patterns: list[str], text: str) -> str | None:
    for pattern in patterns:
        match = re.search(pattern, text, flags=re.IGNORECASE | re.MULTILINE)
        if match:
            return match.group(1).strip()
    return None


def _parse_decimal(raw_value: str) -> Decimal:
    normalized = re.sub(r"[^0-9,.\-]", "", raw_value).replace(",", "")
    return Decimal(normalized)


def _parse_date(raw_value: str):
    raw_value = raw_value.strip()
    for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d/%m/%Y", "%d-%m-%Y", "%b %d %Y", "%B %d %Y"):
        try:
            return datetime.strptime(raw_value, fmt).date()
        except ValueError:
            continue
    raise ValueError(f"Unable to parse invoice date from '{raw_value}'.")


def _extract_vendor_name(text: str) -> str:
    explicit_vendor = _first_match(
        [
            r"^vendor[:\s]+(.+)$",
            r"^supplier[:\s]+(.+)$",
            r"^bill from[:\s]+(.+)$",
        ],
        text,
    )
    if explicit_vendor:
        return explicit_vendor

    for line in text.splitlines():
        candidate = line.strip()
        if not candidate:
            continue
        lowered = candidate.lower()
        if any(keyword in lowered for keyword in ("invoice", "date", "total", "subtotal", "tax")):
            continue
        return candidate

    raise ValueError("Unable to determine vendor name from OCR text.")


def _extract_invoice_number(text: str) -> str:
    value = _first_match(
        [
            r"invoice\s*(?:number|no|#)?[:\s-]+([A-Z0-9-]+)",
            r"\bINV[-\s:#]*([A-Z0-9-]+)",
        ],
        text,
    )
    if not value:
        raise ValueError("Unable to determine invoice number from OCR text.")
    return value


def _extract_invoice_date(text: str):
    value = _first_match(
        [
            r"invoice\s*date[:\s]+([A-Za-z0-9,/\- ]+)",
            r"date[:\s]+([A-Za-z0-9,/\- ]+)",
        ],
        text,
    )
    if not value:
        raise ValueError("Unable to determine invoice date from OCR text.")
    return _parse_date(value)


def _extract_currency(text: str) -> str:
    detected = _first_match(
        [
            r"currency[:\s]+([A-Z]{3})",
            r"\b(USD|EUR|GBP|JPY|TWD|SGD|AUD|CAD|IDR|MYR|THB|CNY|INR)\b",
            r"\b(RP|RUPIAH)\b",
            r"\b(NT\$)\b",
            r"\b(RM)\b",
            r"\b(BAHT)\b",
            r"\b(RMB|YUAN)\b",
            r"\b(RUPEE)\b",
        ],
        text,
    )
    if not detected:
        return "USD"

    normalized = detected.upper()
    aliases = {
        "RP": "IDR",
        "RUPIAH": "IDR",
        "NT$": "TWD",
        "RM": "MYR",
        "BAHT": "THB",
        "RMB": "CNY",
        "YUAN": "CNY",
        "RUPEE": "INR",
    }
    return aliases.get(normalized, normalized)


def _extract_payment_terms(text: str) -> str | None:
    return _first_match([r"payment\s*terms?[:\s]+(.+)$"], text)


def _extract_amount(text: str, labels: tuple[str, ...], default: Decimal | None = None) -> Decimal | None:
    for label in labels:
        match = re.search(
            rf"(?im)^\s*{re.escape(label)}\b[:\s$]*([-+]?\$?[0-9,]+(?:\.[0-9]{{2}})?)",
            text,
        )
        if match:
            return _parse_decimal(match.group(1))
    return default


def _extract_line_items(text: str, subtotal: Decimal) -> list[InvoiceLineItem]:
    line_items: list[InvoiceLineItem] = []

    explicit_pattern = re.compile(
        r"(?im)^(?P<description>[A-Za-z0-9\s\-/(),.&]+?)\s+qty[:\s]*(?P<quantity>\d+(?:\.\d+)?)\s+"
        r"(?:unit\s*price|price)[:\s$]*(?P<unit>[0-9,]+(?:\.[0-9]{2})?)\s+"
        r"(?:amount|subtotal|line\s*total)[:\s$]*(?P<amount>[0-9,]+(?:\.[0-9]{2})?)$"
    )
    for match in explicit_pattern.finditer(text):
        quantity = _parse_decimal(match.group("quantity"))
        unit_price = _parse_decimal(match.group("unit"))
        amount = _parse_decimal(match.group("amount"))
        line_items.append(
            InvoiceLineItem(
                description=match.group("description").strip(),
                quantity=quantity,
                unit_price=unit_price,
                amount=amount,
            )
        )

    if line_items:
        return line_items

    table_pattern = re.compile(
        r"(?im)^(?P<description>[A-Za-z][A-Za-z0-9\s\-/(),.&]{2,}?)\s+"
        r"(?P<quantity>\d+(?:\.\d+)?)\s+"
        r"(?P<unit>[0-9,]+(?:\.[0-9]{2})?)\s+"
        r"(?P<amount>[0-9,]+(?:\.[0-9]{2})?)$"
    )
    for match in table_pattern.finditer(text):
        line_items.append(
            InvoiceLineItem(
                description=match.group("description").strip(),
                quantity=_parse_decimal(match.group("quantity")),
                unit_price=_parse_decimal(match.group("unit")),
                amount=_parse_decimal(match.group("amount")),
            )
        )

    if line_items:
        return line_items

    return [
        InvoiceLineItem(
            description="Imported invoice amount",
            quantity=Decimal("1"),
            unit_price=subtotal,
            amount=subtotal,
        )
    ]
